#!/bin/sh
# rc2udev.sh - run on the device.
#
# Collects the /dev permissions Android sets at runtime (chown/chmod in init
# *.rc files, plus vendor/odm ueventd.rc which droid-hal's makeudev does not
# see when the vendor partition is prebuilt) and prints equivalent udev rules,
# so the nodes have the right owner before any HAL opens them.
#
# Usage: sh rc2udev.sh > /tmp/999-droid-init-dev.rules
# Review the output, then copy it to droid-configs sparse/lib/udev/rules.d/
# (the name sorts after 999-android-system.rules, so it wins on conflicts).

FILES=$(ls /init*.rc /system/etc/init/*.rc /system/etc/init/hw/*.rc \
           /vendor/etc/init/*.rc /vendor/etc/init/hw/*.rc \
           /odm/etc/init/*.rc /product/etc/init/*.rc \
           /usr/libexec/droid-hybris/system/etc/init/*.rc \
           /vendor/ueventd.rc /odm/ueventd.rc 2>/dev/null)

echo "# Generated by rc2udev.sh from Android init chown/chmod and ueventd rules"
echo

awk '
function add(path, what, val) {
    if (path !~ /^\/dev\// || path ~ /[$]/) return
    if (!(path in seen)) { seen[path] = 1; order[n++] = path }
    if (what == "mode") mode[path] = val
    else { owner[path] = val; group[path] = grp }
    origin[path] = origin[path] " " FILENAME ":" FNR "(" section ")"
    if (section ~ /property:|=/) cond[path] = 1
}
FNR == 1 { section = "" }
{ sub(/#.*/, "") }
$1 == "on" { section = $2; for (i = 3; i <= NF; i++) section = section " " $i; next }
$1 == "service" { section = "service " $2; next }
FILENAME ~ /ueventd\.rc$/ && $1 ~ /^\/dev\// && NF == 4 {
    section = "ueventd"; grp = $4; add($1, "owner", $3); add($1, "mode", $2); next
}
$1 == "chown" && NF >= 4 { grp = $3; add($4, "owner", $2) }
$1 == "chmod" && NF >= 3 { add($3, "mode", $2) }
END {
    for (i = 0; i < n; i++) {
        p = order[i]
        printf "%s|%s|%s|%s|%s|%s\n", p, mode[p], owner[p], group[p], cond[p] ? "cond" : "", origin[p]
    }
}' $FILES | while IFS='|' read -r path mode owner group cond origin; do
    # Only real device nodes (skips sockets, cgroup/cpuset dirs, ...); keep globs
    case "$path" in
        *'*'*) ;;
        *) [ -c "$path" ] || [ -b "$path" ] || continue ;;
    esac
    rule="ENV{DEVNAME}==\"$path\""
    [ -n "$owner" ] && rule="$rule, OWNER=\"$owner\", GROUP=\"$group\""
    [ -n "$mode" ] && rule="$rule, MODE=\"$mode\""
    echo "#$origin"
    if [ -n "$cond" ]; then
        echo "# set from a property trigger, check before enabling:"
        echo "#$rule"
    else
        echo "$rule"
    fi
done
